[build]
  base = "."
  
  command = """
    sh ./build.sh &&
    cd output &&
    corepack enable &&
    pnpm install --frozen-lockfile &&
    pnpm build:storybook
  """
  
  publish = "output/storybook-static"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "9.7.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"