packages:
  - .templates/*
  - packages/*
  - www

catalog:
  '@storybook/addon-essentials': ^8.4.5
  '@storybook/addon-interactions': ^8.4.5
  '@storybook/addon-links': ^8.4.5
  '@storybook/blocks': ^8.4.5
  '@storybook/react': ^8.4.5
  '@storybook/react-vite': ^8.4.5
  '@storybook/test': ^8.4.5
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.0.1
  '@vitest/coverage-v8': ^2.1.8
  happy-dom: ^15.7.4
  knip: ^5.34.1
  storybook: ^8.4.7
  tsup: ^8.3.5
  typescript: ^5.6.3
  vitest: ^2.1.8

catalogs:
  react:
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.1
    react: ^18.3.1
    react-dom: ^18.3.1
