packages:
  - .templates/*
  - packages/*
  - www

catalog:
  '@storybook/addon-essentials': ^8.4.5
  '@storybook/addon-interactions': ^8.4.5
  '@storybook/addon-links': ^8.4.5
  '@storybook/blocks': ^8.4.5
  '@storybook/react': ^8.4.5
  '@storybook/react-vite': ^8.4.5
  '@storybook/test': ^8.4.5
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.0.1
  '@testing-library/user-event': ^14.6.1
  '@vanilla-extract/css': ^1.14.1
  '@vanilla-extract/esbuild-plugin': ^2.3.15
  '@vanilla-extract/vite-plugin': ^5.0.1
  '@vitest/browser': ^3.1.3
  '@vitest/coverage-v8': ^3.1.3
  happy-dom: ^15.7.4
  knip: ^5.34.1
  playwright: ^1.52.0
  storybook: ^8.4.7
  tsup: ^8.4.0
  typescript: ^5.6.3
  vite: ^6.3.5
  vitest: ^3.1.3
  vitest-browser-react: ^0.1.1