import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

export default {
  overview: [{ type: 'autogenerated', dirName: 'overview' }],
  components: [{ type: 'autogenerated', dirName: 'components' }],
} satisfies SidebarsConfig;
