name: CI

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup-action
      - name: Lint
        run: pnpm --filter="...[origin/${{ github.base_ref }}]" "/lint:*/"
      - name: Test
        run: pnpm --filter="...[origin/${{ github.base_ref }}]" test
      - name: Type check
        run: pnpm --filter="...[origin/${{ github.base_ref }}]" typecheck
      - name: Build
        run: pnpm --filter="...[origin/${{ github.base_ref }}]" build
